FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ./WebApi/WebApi.csproj ./WebApi/
COPY ./Infrastructure/Infrastructure.csproj ./Infrastructure/
COPY ./CoreApp/CoreApp.csproj ./CoreApp/
RUN dotnet restore "WebApi/WebApi.csproj"

COPY . .
RUN dotnet build "WebApi/WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApi/WebApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApi.dll"]